### ISSUE TITLE
Returns slip is missing wrapper for print view. 

### ISSUE THREAD

**Issue by aislingbrock** [mothership-ec/mothership#53]

**Comment by GraceAshton89** [comment]
When making a return, at then end of the process it asks you to print. Print looks weird as wrapper is missing:

http://grace:1040/account/return/complete/1

**Comment by GraceAshton89** [comment]
THis issue is in mothership-returns. Closing here.

**Comment by GraceAshton89** [comment]
THis issue is in mothership-returns. Closing here.
